### ISSUE TITLE
Unexpected behavior when n is null?

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/contingencytables#1]
Hi, Morten! I've just observed a certain behavior on some functions. I don't know if it's intentional and I am misunderstanding the arguments on those functions, but even in that case that's something that might be best documented somewhere so other users don't make the same mistake as me.

If it _is_ a bug, it's also simple to fix.

In any case, I appreciate the clarification, as so far all the functions I've added to the package show the same behavior.

# Summary

On some functions, providing `X` but no `n` makes the function ignore `X` and replace it with a set value unknown to the user (unless they inpect the source code).

# Code to reproduce

```r
# Installing and loading contingencytables
install.packages("remotes")
remotes::install_github("ocbe-uio/contingencytables", ref="9a10250b")
library(contingencytables)

# Loading the Chapter 2 functions
load_chapter(2)

# Using an example function from Chapter 2
AgrestiCoull_CI_1x2(1)
AgrestiCoull_CI_1x2(1000)
```

# Expected behavior

I would expect `AgrestiCoull_CI_1x2(1)` to yield a different estimate from `AgrestiCoull_CI_1x2(1000)`. Specifically, I was expecting `n = X` if `n` is not provided so the output would be

```r
r$> AgrestiCoull_CI_1x2(1, 1)                                                
[1] The Agresti-Coull CI: estimate = 0.6000 (95% CI 0.1706 to 1.0000)

r$> AgrestiCoull_CI_1x2(1000, 1000)                                          
[1] The Agresti-Coull CI: estimate = 0.9980 (95% CI 0.9952 to 1.0000)
```

# Observed behavior

```r
r$> AgrestiCoull_CI_1x2(1)                                                   
[1] The Agresti-Coull CI: estimate = 0.4693 (95% CI 0.4271 to 0.5115)

r$> AgrestiCoull_CI_1x2(1000)                                                
[1] The Agresti-Coull CI: estimate = 0.4693 (95% CI 0.4271 to 0.5115)
```

# Cause for the observed behavior

The code below basically says that if `n` is not provided, `X` is replaced with 250 and `n` with `533`, apparently mimicking an example from Singh et. al., 2010.

https://github.com/ocbe-uio/contingencytables/blob/9a10250bb97b5d3c899eb880b3cb3e290b6305f2/R/AgrestiCoull_CI_1x2.R#L19-L25

**Comment by mortenfagerland** [comment]
This is a bug. The function should produce an error if you try to call on it with less than 2 input variables. The code is not idiot-proof, and I think this is not, in fact, implemented in most of the functions.


Thanks for noticing this!


Morten



________________________________

**Comment by wleoncio** [comment]
> The function should produce an error if you try to call on it with less than 2 input variables.

Got it, I'll change the code to reflect this. Not to lose information, I think the removed lines will look very nice as function examples, so I'll take care of that as well.

**Comment by mortenfagerland** [comment]
?Great!


________________________________
