### ISSUE TITLE
Different output on Wald_CI_1x2

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/contingencytables#11]
# Summary

The `Wald_CI_1x2()` function prints output on a different format than other functions.

# Steps to reproduce

```r
# Installing and loading contingencytables
install.packages("remotes")
remotes::install_github("ocbe-uio/contingencytables", ref="9a10250b")
library(contingencytables)

# Loading the Chapter 2 functions
load_chapter(2)

# Comparing the printed output of two functions
Wald_CI_1x2(10, 30)
AgrestiCoull_CI_1x2(10, 30)
```

# Observed behavior

Notice how the formats of the two outputs are different. Here's a screenshot from my machine:

![image](https://user-images.githubusercontent.com/8234768/98383943-6be9ff00-204d-11eb-800d-514855c16525.png)

# Expected behavior

I would expect the printed output of all these functions to be similar.

# Cause for the expected behavior

This is basically caused by one line that every other function has to print (i.e., `quote=FALSE`), but `Wald_CI_1x2` doesn't. Is this by design or something that could be changed in the name of standardization?

**Comment by mortenfagerland** [comment]
It's not by design. Probably just a slip. Please change it to standard.


Morten



________________________________
